name: wefellowship
description: wefellowship app helps message believers connect share & reach  globally.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  fpdart: ^0.5.0
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  vector_graphics: ^1.1.4
  vector_graphics_codec: ^1.1.4
  vector_graphics_compiler: ^1.1.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/icons/types/

  fonts:
    # Muli typeface
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800
        - asset: assets/fonts/Muli-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Muli-Semi-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Muli-Light.ttf
          weight: 500
        - asset: assets/fonts/Muli-LightItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Muli-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Muli.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
