// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0WRirIm27YFgPJvlT4bavwWQaBX0qn0w',
    appId: '1:213182961253:web:30395495d497765e0cd88c',
    messagingSenderId: '213182961253',
    projectId: 'wefellowship-dev',
    authDomain: 'wefellowship-dev.firebaseapp.com',
    storageBucket: 'wefellowship-dev.appspot.com',
    measurementId: 'G-G0EZEPYJ5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsfUFMqvX7Z0Pn1zgTbLZBP4dLfaXss8',
    appId: '1:213182961253:android:dc27b0d788ae90440cd88c',
    messagingSenderId: '213182961253',
    projectId: 'wefellowship-dev',
    storageBucket: 'wefellowship-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8fGAmFYHxHSL9SwSb4JBv1wdFPEwrtTY',
    appId: '1:213182961253:ios:a2636ca96d5affb00cd88c',
    messagingSenderId: '213182961253',
    projectId: 'wefellowship-dev',
    storageBucket: 'wefellowship-dev.appspot.com',
    iosClientId: '213182961253-6iuhf86e6vnjoivqj1194c8si49152h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wefellowship',
  );
}
